name: Verify Content

on:
  pull_request:
  push:
    paths:
    - '.github/workflows/content.yml'
    - 'data/src/**'
  workflow_dispatch:


jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - run: npm i

    - name: Pack
      run: npm run build
